### ISSUE TITLE
Does this work with EnvKey v2?

### ISSUE THREAD

**Issue by sscarduzio** [envkey/envkey-python#11]
I see some references to envkey v1 in the readme, I tried to use it on v2 and it kinda works. But the API is different for loading. Where should I look for documentation?

**Comment by danenania** [comment]
Hey @sscarduzio yes, it should be working in exactly the same way for v2. What differences are you finding in the API?

**Comment by sscarduzio** [comment]
For example, I'm reusing a load [snippet](https://github.com/envkey/envkey-python#disabling-autoload) from README.md, but get an exception.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/1327189/163942861-fdefba3a-9a09-43eb-a323-dababca5eed2.png">

**Comment by danenania** [comment]
I see. The `.env` file/`ENVKEY` loading is now handled by the embedded envkey-source binary rather than the python package, so that aspect of the API did indeed change (sorry, was mistaken to say it hadn't changed at all). If you call `load` like this instead, it should work:

```python
envkey.load(cache_enabled=True)
```

The README in this repo is for v1. [You can find the v2 README here with updated examples.](https://github.com/envkey/envkey/tree/main/public/sdks/languages-and-frameworks/python)

**Comment by sscarduzio** [comment]
Oh ok. V2 has SDKs in the same repo of the main one so... Worth having a link in this repo README.md maybe?

**Comment by danenania** [comment]
Yeah, there is a link in the paragraph under the **v2** heading, but it probably needs to be more visible. 👍

**Comment by danenania** [comment]
Is that better @sscarduzio?

**Comment by sscarduzio** [comment]
You are right, I didn't see that. Thanks for making it more evident 👍 

BTW Amazing tool, I really like it. Thanks for your work!
